# Generated by Django 2.2.24 on 2021-10-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port',
        ),
    ]
