# Generated by Django 2.2.24 on 2021-10-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(default='宝塚大劇場', max_length=200),
            preserve_default=False,
        ),
    ]
