# Generated by Django 2.2.24 on 2021-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='ticket',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
    ]
